#%RAML 0.8
title: demoapi
baseUri: coap://api.sylft.io/
version: 0.1
schemas:
- value: value_schema.json
/temp:
  get:
    description: Return temperature (as string)
    responses:
      205:
        body:
          application/x-msgpack:
            schema: value
/led:
  get:
    description: Return value of led
    responses:
      205:
        body:
          application/x-msgpack:
            schema: value
/led/on:
  post:
    description: Turn LED on
/led/off:
  post:
    description: Turn LED off
