#%RAML 0.8
title: demoapi
baseUri: coap://api.sylft.io/
version: 0.1
schemas:
- value: value_schema.json
- partner: partner_schema.json
/rotary:
  get:
    description: Return value of rotary
    responses:
      205:
        body:
          application/x-msgpack:
            schema: value
/flash:
  post:
    description: Makes somthing flashy. No response, no body
/partner:
  post:
    description: Set partner ID and IP address
    body:
      application/x-msgpack:
        schema: partner
