
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part header



    #include "Arduino.h"

#include "microcoap/coap.h"

// include data structure headers
#include "value.h"

// struct DEMOAPI__value
#include "value.h"



//
// CoAP Application level handlers
//

// -- GET  /temp

struct DEMOAPI__demoapi__get___temp_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__get___temp_resp {
    coap_responsecode_t  response_code;
    struct {

  
        // data struct for response code 205
        struct DEMOAPI__value  value_205;

    } data;
};

// -- Application level handler for GET to /temp
bool DEMOAPI__demoapi__get___temp(
    struct DEMOAPI__demoapi__get___temp_req *req,
    struct DEMOAPI__demoapi__get___temp_resp *resp);


// -- GET  /led

struct DEMOAPI__demoapi__get___led_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__get___led_resp {
    coap_responsecode_t  response_code;
    struct {

  
        // data struct for response code 205
        struct DEMOAPI__value  value_205;

    } data;
};

// -- Application level handler for GET to /led
bool DEMOAPI__demoapi__get___led(
    struct DEMOAPI__demoapi__get___led_req *req,
    struct DEMOAPI__demoapi__get___led_resp *resp);


// -- POST  /led/on

struct DEMOAPI__demoapi__post___led_on_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__post___led_on_resp {
    coap_responsecode_t  response_code;
    struct {

    } data;
};

// -- Application level handler for POST to /led/on
bool DEMOAPI__demoapi__post___led_on(
    struct DEMOAPI__demoapi__post___led_on_req *req,
    struct DEMOAPI__demoapi__post___led_on_resp *resp);


// -- POST  /led/off

struct DEMOAPI__demoapi__post___led_off_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__post___led_off_resp {
    coap_responsecode_t  response_code;
    struct {

    } data;
};

// -- Application level handler for POST to /led/off
bool DEMOAPI__demoapi__post___led_off(
    struct DEMOAPI__demoapi__post___led_off_req *req,
    struct DEMOAPI__demoapi__post___led_off_resp *resp);


