// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// endpoints

#include "microcoap/coap.h"

// enumerate all single resources as endpoint_path types

static const coap_endpoint_path_t DEMOAPI__demoapi__paths__rotary = {1, {"rotary"}};
static const coap_endpoint_path_t DEMOAPI__demoapi__paths__flash = {1, {"flash"}};
static const coap_endpoint_path_t DEMOAPI__demoapi__paths__well_known_core = {2, {".well-known", "core"}};

// define handler functions

int DEMOAPI__demoapi__handle_get___rotary(coap_rw_buffer_t *scratch,
    const coap_packet_t *inpkt, coap_packet_t *outpkt,
    uint8_t id_hi, uint8_t id_lo);

int DEMOAPI__demoapi__handle_get_well_known_core(coap_rw_buffer_t *scratch,
    const coap_packet_t *inpkt, coap_packet_t *outpkt,
    uint8_t id_hi, uint8_t id_lo);

int DEMOAPI__demoapi__handle_post___flash(coap_rw_buffer_t *scratch,
    const coap_packet_t *inpkt, coap_packet_t *outpkt,
    uint8_t id_hi, uint8_t id_lo);


// define array with all endpoints
extern const coap_endpoint_t endpoints[] =
{

    {COAP_METHOD_GET, DEMOAPI__demoapi__handle_get_well_known_core, &DEMOAPI__demoapi__paths__well_known_core, "ct=40"},
    {COAP_METHOD_GET, DEMOAPI__demoapi__handle_get___rotary, &DEMOAPI__demoapi__paths__rotary, "ct=42"},	/* Return value of rotary */
    {COAP_METHOD_POST, DEMOAPI__demoapi__handle_post___flash, &DEMOAPI__demoapi__paths__flash, "ct=42"},	/* Makes somthing flashy. No response, no body */
    {(coap_method_t)0, NULL, NULL, NULL}
};
