
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part header



    #include "Arduino.h"

#include "microcoap/coap.h"

// include data structure headers
#include "value.h"

// struct DEMOAPI__value
#include "value.h"



//
// CoAP Application level handlers
//

// -- GET  /rotary

struct DEMOAPI__demoapi__get___rotary_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__get___rotary_resp {
    coap_responsecode_t  response_code;
    struct {

  
        // data struct for response code 205
        struct DEMOAPI__value  value_205;

    } data;
};

// -- Application level handler for GET to /rotary
bool DEMOAPI__demoapi__get___rotary(
    struct DEMOAPI__demoapi__get___rotary_req *req,
    struct DEMOAPI__demoapi__get___rotary_resp *resp);


// -- POST  /flash

struct DEMOAPI__demoapi__post___flash_req {
    struct {

    } data;
};

struct DEMOAPI__demoapi__post___flash_resp {
    coap_responsecode_t  response_code;
    struct {

    } data;
};

// -- Application level handler for POST to /flash
bool DEMOAPI__demoapi__post___flash(
    struct DEMOAPI__demoapi__post___flash_req *req,
    struct DEMOAPI__demoapi__post___flash_resp *resp);


