
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.


#include "Arduino.h"
#include <ArduinoJson.h>

#include "value.h"

StaticJsonBuffer<512> DEMOAPI__jsonBuffer;

void DEMOAPI__value_clean(struct DEMOAPI__value *self) {
	self->v = 0;
}

int DEMOAPI__value_parse(struct DEMOAPI__value *self, const uint8_t *input_buf, size_t sz_input_buf) {
	JsonObject& root = DEMOAPI__jsonBuffer.parseObject(input_buf);

	if (!root.success())
		return 1;

  if (root.containsKey("v") && root.is<int>("v")) {
		self->v = root["v"];
	}

	return 0;
}

size_t DEMOAPI__value_serialize(const struct DEMOAPI__value *self, uint8_t *output_buf, size_t sz_output_buf) {
		JsonObject& root = DEMOAPI__jsonBuffer.createObject();
		root["v"] = self->v;

		return root.printTo((char*)output_buf, sz_output_buf);
}

void DEMOAPI__value_init(struct DEMOAPI__value *self) {
    self->DEMOAPI__value_clean = &DEMOAPI__value_clean;
    self->DEMOAPI__value_parse = &DEMOAPI__value_parse;
    self->DEMOAPI__value_serialize = &DEMOAPI__value_serialize;
    self->DEMOAPI__value_clean(self);
}

//
